apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: abook-frontend-dep
  labels:
    name: abook-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abook-frontend-dep
  template:
    metadata:
      labels:
        app: abook-frontend-dep
    spec:
      containers:
        - name: abook-frontend-dep
          image: '9009fa25-kr1-registry.container.nhncloud.com/tmaxrg-nia-registry/abook-frontend:v1.0.5.1'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: VITE_SERVER_URL
              value: 'http://abook-backend-service:8080'
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: registry-credential
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
